.PHONY: all

all:
	$(MAKE) -C src/shiro				-f MAKEFILE
	$(MAKE) -C src/shiro/libs/stdio		-f MAKEFILE
	$(MAKE) -C src/shiro/libs/stdgui	-f MAKEFILE
	$(MAKE) -C src/shiro/libs/math		-f MAKEFILE
	$(MAKE) -C src/shiro/libs/bignum	-f MAKEFILE

	$(MAKE) -C src/interpreter	-f MAKEFILE
	$(MAKE) -C src/compiler		-f MAKEFILE

clean debug release:
	$(MAKE) -C src/shiro				-f MAKEFILE $@
	$(MAKE) -C src/shiro/libs/stdio		-f MAKEFILE $@
	$(MAKE) -C src/shiro/libs/stdgui	-f MAKEFILE $@
	$(MAKE) -C src/shiro/libs/math		-f MAKEFILE $@
	$(MAKE) -C src/shiro/libs/bignum	-f MAKEFILE $@

	$(MAKE) -C src/interpreter	-f MAKEFILE $@
	$(MAKE) -C src/compiler		-f MAKEFILE $@
