#==============================================================================
# MAKEFILE para o lib/bignum.dll
#==============================================================================
# Executáveis usados
CC = gcc.exe
LD = ld.exe

# Diretório com os .h usados
INC = -I../sdk/include -Igmp-6.1.1/include

# Diretórios dos .a/.lib usados
LIB_GMP = -Lgmp-6.1.1/lib/
LIBDIR = -L../bin

LIBS = -lshiro -lgmp

# Flag para o compilador
CFLAGS = -Wall

# Variáveis para a compilação do arquivo de Debug
LIBDIR_DEBUG	= $(LIBDIR)/Debug $(LIB_GMP)
CFLAGS_DEBUG 	= $(CFLAGS) -Wunreachable-code -g -D__DEBUG__
OUTDIR_DEBUG 	= ../bin/Debug
OUT_DEBUG 		= $(OUTDIR_DEBUG)/lib/bignum.dll
OBJDIR_DEBUG 	= obj/Debug

# Variáveis para a compilação do arquivo definitivo
LIBDIR_RELEASE	= $(LIBDIR)/Release $(LIB_GMP)
CFLAGS_RELEASE 	= $(CFLAGS) -O3
OUTDIR_RELEASE 	= ../bin/Release
OUT_RELEASE 		= $(OUTDIR_RELEASE)/lib/bignum.dll
OBJDIR_RELEASE	= obj/Release

#==============================================================================
# Regras de compilação
#==============================================================================
all: pre_debug debug pre_release release
.PHONY: all

#------------------------------------------------------------------------------
# Regra para os arquivos de objeto do Debug
#------------------------------------------------------------------------------
pre_debug:
	test -d $(OBJDIR_DEBUG) || mkdir "$(OBJDIR_DEBUG)"

debug:
	$(CC) $(CFLAGS_DEBUG) -o $(OUT_DEBUG) -shared $(INC) src/bignum.c $(LIBDIR_DEBUG) $(LIBS)
#------------------------------------------------------------------------------
# Regra para os arquivos de objeto do Release
#------------------------------------------------------------------------------
pre_release:
	test -d $(OBJDIR_RELEASE) || mkdir "$(OBJDIR_RELEASE)"

release:
		$(CC) $(CFLAGS_RELEASE) -o $(OUT_RELEASE) -shared $(INC) src/bignum.c $(LIBDIR_RELEASE) $(LIBS)

#------------------------------------------------------------------------------
# Regras para limpeza dos arquivos compilados
#------------------------------------------------------------------------------
clean_debug:
	rm -rf $(OBJDIR_DEBUG)
	rm -f $(OUT_DEBUG)

clean_release:
	rm -rf $(OBJDIR_DEBUG)
	rm -f $(OUT_RELEASE)

clean: clean_debug clean_release
		rm -rf obj
