#==============================================================================
# MAKEFILE para o lib/stdio.dll
#==============================================================================
# Executáveis usados
CC = gcc.exe
LD = ld.exe

# Diretório com os .h usados
INC = -I../sdk/include
LIB = -L../bin

# Flag para o compilador
CFLAGS = -Wall

# Variáveis para a compilação do arquivo de Debug
LIB_DEBUG			= $(LIB)/Debug
CFLAGS_DEBUG 	= $(CFLAGS) -Wunreachable-code -g -D__DEBUG__
OUTDIR_DEBUG 	= ../bin/Debug
OUT_DEBUG 		= $(OUTDIR_DEBUG)/lib/stdio.
OBJDIR_DEBUG 	= obj/Debug

# Variáveis para a compilação do arquivo definitivo
LIB_RELEASE			= $(LIB)/Release
CFLAGS_RELEASE 	= $(CFLAGS) -O2
OUTDIR_RELEASE 	= ../bin/Release
OUT_RELEASE 		= $(OUTDIR_RELEASE)/lib/stdio.
OBJDIR_RELEASE	= obj/Release

#==============================================================================
# Regras de compilação
#==============================================================================
all: pre_debug debug pre_release release
.PHONY: all

#------------------------------------------------------------------------------
# Regra para os arquivos de objeto do Debug
#------------------------------------------------------------------------------
pre_debug:
	test -d $(OBJDIR_DEBUG) || mkdir "$(OBJDIR_DEBUG)"

debug:
	$(CC) $(CFLAGS_DEBUG) -shared -o $(OUT_DEBUG) $(INC) src/stdio.c $(LIB_DEBUG) -lshiro

#------------------------------------------------------------------------------
# Regra para os arquivos de objeto do Release
#------------------------------------------------------------------------------
pre_release:
	test -d $(OBJDIR_RELEASE) || mkdir "$(OBJDIR_RELEASE)"

release:
	$(CC) $(CFLAGS_RELEASE) -shared -o $(OUT_RELEASE) $(INC) src/stdio.c $(LIB_RELEASE) -lshiro

#------------------------------------------------------------------------------
# Regras para limpeza dos arquivos compilados
#------------------------------------------------------------------------------
clean_debug:
	rm -rf $(OBJDIR_DEBUG)
	rm -f $(OUT_DEBUG)

clean_release:
	rm -rf $(OBJDIR_DEBUG)
	rm -f $(OUT_RELEASE)

clean: clean_debug clean_release
		rm -rf obj
