#==============================================================================
# MAKEFILE para o lib/stdgui.dll
#==============================================================================
# Executáveis usados
CC = gcc.exe
LD = ld.exe

# Diretório com os .h usados
INC = -I../sdk/include -Iinclude -Iglfw-3.2.1/include -Iglew-2.0.0/include

# Diretórios dos .a/.lib usados
LIB_GLFW = -Lglfw-3.2.1/lib-mingw
LIB_GLEW = -Lglew-2.0.0/lib/Release/Win32
LIBDIR = -L../bin

LIBS = -lshiro -lglfw3 -lglew32s -lopengl32 -lgdi32 -luser32 -lwinmm

# Flag para o compilador
CFLAGS = -Wall -DGLEW_STATIC

# Variáveis para a compilação do arquivo de Debug
LIBDIR_DEBUG	= $(LIBDIR)/Debug $(LIB_GLFW) $(LIB_GLEW)
CFLAGS_DEBUG 	= $(CFLAGS) -Wunreachable-code -g -D__DEBUG__
OUTDIR_DEBUG 	= ../bin/Debug
OUT_DEBUG 		= $(OUTDIR_DEBUG)/lib/stdgui.dll
OBJDIR_DEBUG 	= obj/Debug

# Variáveis para a compilação do arquivo definitivo
LIBDIR_RELEASE	= $(LIBDIR)/Release $(LIB_GLFW) $(LIB_GLEW)
CFLAGS_RELEASE 	= $(CFLAGS) -O3
OUTDIR_RELEASE 	= ../bin/Release
OUT_RELEASE 		= $(OUTDIR_RELEASE)/lib/stdgui.dll
OBJDIR_RELEASE	= obj/Release

#==============================================================================
# Regras de compilação
#==============================================================================
all: pre_debug debug pre_release release
.PHONY: all

#------------------------------------------------------------------------------
# Regra para os arquivos de objeto do Debug
#------------------------------------------------------------------------------
pre_debug:
	test -d $(OBJDIR_DEBUG) || mkdir "$(OBJDIR_DEBUG)"

$(OBJDIR_DEBUG)/stdgui.o: src/stdgui.c
	$(CC) $(CFLAGS_DEBUG) -o $@ $(INC) -c $<

$(OBJDIR_DEBUG)/advgui.o: src/advgui.c
	$(CC) $(CFLAGS_DEBUG) -o $@ $(INC) -c $<

debug: $(OBJDIR_DEBUG)/stdgui.o $(OBJDIR_DEBUG)/advgui.o
	$(CC) $(CFLAGS_DEBUG) -o $(OUT_DEBUG) -shared $^ $(LIBDIR_DEBUG) $(LIBS)
#------------------------------------------------------------------------------
# Regra para os arquivos de objeto do Release
#------------------------------------------------------------------------------
pre_release:
	test -d $(OBJDIR_RELEASE) || mkdir "$(OBJDIR_RELEASE)"

$(OBJDIR_RELEASE)/stdgui.o: src/stdgui.c
		$(CC) $(CFLAGS_RELEASE) -o $@ $(INC) -c $<

$(OBJDIR_RELEASE)/advgui.o: src/advgui.c
		$(CC) $(CFLAGS_RELEASE) -o $@ $(INC) -c $<

release: $(OBJDIR_RELEASE)/advgui.o $(OBJDIR_RELEASE)/stdgui.o
		$(CC) $(CFLAGS_RELEASE) -o $(OUT_RELEASE) $^ -shared $(LIBDIR_RELEASE) $(LIBS)

#------------------------------------------------------------------------------
# Regras para limpeza dos arquivos compilados
#------------------------------------------------------------------------------
clean_debug:
	rm -rf $(OBJDIR_DEBUG)
	rm -f $(OUT_DEBUG)

clean_release:
	rm -rf $(OBJDIR_DEBUG)
	rm -f $(OUT_RELEASE)

clean: clean_debug clean_release
		rm -rf obj
