#==============================================================================
# MAKEFILE para o shiro.dll
#==============================================================================
# Executáveis usados
CC = gcc
LD = gcc

# Diretório com os .h usados
INC = -Iinclude

# Flag para o compilador
CFLAGS = -Wall -DSHIRO_EXPORTS

# Variáveis para a compilação do arquivo de Debug
CFLAGS_DEBUG 	= $(CFLAGS) -Wunreachable-code -g -D__DEBUG__
OUTDIR_DEBUG 	= ../../bin/Win32/Debug
OUT_DEBUG 		= $(OUTDIR_DEBUG)/shiro.dll
OUTLIB_DEBUG 	= $(OUTDIR_DEBUG)/libshiro.a
OBJDIR_DEBUG 	= obj/Debug
OBJS_DEBUG 		= 	$(OBJDIR_DEBUG)/lexer.o \
					$(OBJDIR_DEBUG)/binary.o \
					$(OBJDIR_DEBUG)/compile.o \
					$(OBJDIR_DEBUG)/vm.o \
					$(OBJDIR_DEBUG)/eval.o \
					$(OBJDIR_DEBUG)/stdlib.o

# Variáveis para a compilação do arquivo definitivo
CFLAGS_RELEASE 	= $(CFLAGS) -fexpensive-optimizations -O2
OUTDIR_RELEASE 	= ../../bin/Win32/Release
OUT_RELEASE    	= $(OUTDIR_RELEASE)/shiro.dll
OUTLIB_RELEASE 	= $(OUTDIR_RELEASE)/libshiro.a
OBJDIR_RELEASE 	= obj/Release
OBJS_RELEASE 	= $(OBJDIR_RELEASE)/lexer.o \
				$(OBJDIR_RELEASE)/binary.o \
				$(OBJDIR_RELEASE)/compile.o \
				$(OBJDIR_RELEASE)/vm.o \
				$(OBJDIR_RELEASE)/eval.o \
				$(OBJDIR_RELEASE)/stdlib.o
#==============================================================================
# Regras de compilação
#==============================================================================
all: pre_debug debug pre_release release
.PHONY: all

#------------------------------------------------------------------------------
# Regra para os arquivos de objeto do Debug
#------------------------------------------------------------------------------
$(OBJDIR_DEBUG)/%.o: %.c
	$(CC) -c $(INC) -o $@ $< $(CFLAGS_DEBUG)

pre_debug:
	test -d $(OBJDIR_DEBUG) || mkdir "$(OBJDIR_DEBUG)"
	test -d $(OUTDIR_DEBUG) || mkdir "$(OUTDIR_DEBUG)"

debug: $(OBJS_DEBUG)
	$(LD) -shared $^ -o $(OUT_DEBUG) -Wl,--out-implib,$(OUTLIB_DEBUG) $(CFLAGS_DEBUG)

#------------------------------------------------------------------------------
# Regra para os arquivos de objeto do Release
#------------------------------------------------------------------------------
$(OBJDIR_RELEASE)/%.o: %.c
	$(CC) -c $(INC) -o $@ $< $(CFLAGS_RELEASE)

pre_release:
	test -d $(OBJDIR_RELEASE) || mkdir "$(OBJDIR_RELEASE)"
	test -d $(OUTDIR_RELEASE) || mkdir "$(OUTDIR_RELEASE)"

release: $(OBJS_RELEASE)
	$(CC) -shared $^ -o $(OUT_RELEASE) -Wl,--out-implib,$(OUTLIB_RELEASE) $(CFLAGS_RELEASE)

#------------------------------------------------------------------------------
# Regras para limpeza dos arquivos compilados
#------------------------------------------------------------------------------
clean_debug:
	rm -rf $(OBJDIR_DEBUG)
	rm -f $(OUT_DEBUG)

clean_release:
	rm -rf $(OBJDIR_DEBUG)
	rm -f $(OUT_RELEASE)

clean: clean_debug clean_release
		rm -rf obj
